INSERT INTO hashtag (hashtag_name) VALUE('산책');
INSERT INTO hashtag (hashtag_name) VALUE('조깅');
INSERT INTO hashtag (hashtag_name) VALUE('러닝');
INSERT INTO hashtag (hashtag_name) VALUE('조용히');
INSERT INTO hashtag (hashtag_name) VALUE('떠들면서');
INSERT INTO hashtag (hashtag_name) VALUE('혼자');
INSERT INTO hashtag (hashtag_name) VALUE('공원');
INSERT INTO hashtag (hashtag_name) VALUE('도로'); 
INSERT INTO hashtag (hashtag_name) VALUE('한강');
INSERT INTO hashtag (hashtag_name) VALUE('강아지');
 
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE(''); 
-- INSERT INTO hashtag (hashtag_name) VALUE('');
-- INSERT INTO hashtag (hashtag_name) VALUE('');